services:
  ros-helix:
    image: ghcr.io/helix-robotics-ag/ros-helix:iron
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    network_mode: "host"
    privileged: true
    ipc: host
    pid: host
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    volumes:
      - ~/.config/helix:/tmp/config
    devices:
      - /dev/input/js0
    command: su - ros --whitelist-environment=ROS_DOMAIN_ID /run.sh
