version: '3'

services:
  ros-helix:
    image: ghcr.io/helix-robotics-ag/ros-helix:iron
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    network_mode: "host"
    privileged: true
    ipc: host
    pid: host
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    volumes:
      - /home/lab/helix_config:/home/ros/helix_config
    command: su - ros --whitelist-environment=ROS_DOMAIN_ID /run.sh
