tendon_transmission_node:
  ros__parameters:
    pulley_radius: 0.01  # [m]
    # Helix v1:
    # For Motor 0,1,2,3,4,5 decreasing rotor position/positive torque -> contraction
    # For Motor 6,7,8 increasing rotor position/negative torque -> contraction 
    motor_orients: [-1, -1, -1, -1, -1, -1, 1, 1, 1]  # !!!NOTE: OPPOSITE FOR HELIX v0!!!
    tendon_min_lim: -0.1  # [m]
    tendon_max_lim: 0.1  # [m]
    holding_current: 70.0  # [mA]
    # TODO - a better solution for the calibration file
    tendon_calib_file_path: "/colcon_ws/src/helix_transmission/config/tendon_calib.yml"