tendon_transmission_node:
  ros__parameters:
    pulley_radius: 0.01  # [m]
    # For Motor 0,1,2,3,4,5 increasing rotor position/positive torque -> contraction
    # For Motor 6,7,8 decreasing rotor position/negative torque -> contraction 
    motor_orients: [1, 1, 1, 1, 1, 1, -1, -1, -1]
    tendon_min_lim: -0.1
    tendon_max_lim: 0.1
    # TODO - a better solution for the calibration file
    tendon_calib_file_path: "/colcon_ws/src/helix_transmission/config/tendon_calib.yml"