controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    motor_head_joint_position_controller:
      type: position_controllers/JointGroupPositionController

    # motor_head_joint_effort_controller: 
    #   type: effort_controllers/JointGroupEffortController

    motor_head_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

motor_head_joint_position_controller:
  ros__parameters:
    joints: # TODO - descriptive names for joints/motors?
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
      - joint8

# motor_head_joint_effort_controller:
#   ros__parameters:
#     joints:
#       - joint0
#       - joint1
#       - joint2
#       - joint3
#       - joint4
#       - joint5
#       - joint6
#       - joint7
#       - joint8

motor_head_joint_state_broadcaster:
  ros__parameters:
    use_local_topics: True
